// <auto-generated />
using System;
using DadosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DadosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DadosAPI.Model.RespostaAluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean")
                        .HasColumnName("Acertou");

                    b.Property<long>("AlternativaId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlternativaId");

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlunoId");

                    b.Property<int>("AnoProva")
                        .HasColumnType("integer")
                        .HasColumnName("AnoProva");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtualizadoEm");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Dificuldade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Dificuldade");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Disciplina");

                    b.Property<long>("QuestaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("QuestaoId");

                    b.Property<DateTime>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RespondidoEm");

                    b.Property<string>("Vestibular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Vestibular");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("Disciplina");

                    b.HasIndex("RespondidoEm");

                    b.HasIndex("Vestibular");

                    b.HasIndex("AlunoId", "QuestaoId")
                        .IsUnique();

                    b.ToTable("Resposta_Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
