FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["QuestaoAPI.csproj", "./"]
RUN dotnet restore "QuestaoAPI.csproj"
COPY . .
RUN dotnet build "QuestaoAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QuestaoAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "QuestaoAPI.dll"]