CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Provas" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Vestibular" character varying(80) NOT NULL,
    "Ano" integer NOT NULL,
    "Edicao" character varying(40),
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Provas" PRIMARY KEY ("ID")
);

CREATE TABLE "Questoes" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProvaId" bigint NOT NULL,
    "Disciplina" character varying(80) NOT NULL,
    "Materia" character varying(80),
    "Enunciado" text NOT NULL,
    "Dificuldade" character varying(20),
    "Numero" integer NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Questoes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Questoes_Provas_ProvaId" FOREIGN KEY ("ProvaId") REFERENCES "Provas" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Alternativas" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "QuestaoId" bigint NOT NULL,
    "Letra" character varying(1) NOT NULL,
    "Texto" character varying(500) NOT NULL,
    "Correta" boolean NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Alternativas" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Alternativas_Questoes_QuestaoId" FOREIGN KEY ("QuestaoId") REFERENCES "Questoes" ("ID") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Alternativas_QuestaoId_Letra" ON "Alternativas" ("QuestaoId", "Letra");

CREATE UNIQUE INDEX "IX_Provas_Vestibular_Ano_Edicao" ON "Provas" ("Vestibular", "Ano", "Edicao");

CREATE UNIQUE INDEX "IX_Questoes_ProvaId_Numero" ON "Questoes" ("ProvaId", "Numero");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622071340_InitialQuestao', '9.0.1');

COMMIT;

