CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Professores" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    siape character varying(7) NOT NULL,
    "primeiroNome" character varying(80) NOT NULL,
    "ultimoNome" character varying(80) NOT NULL,
    email text NOT NULL,
    disciplina character varying(80) NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Professores" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "IX_Professores_email" ON "Professores" (email);

CREATE UNIQUE INDEX "IX_Professores_siape" ON "Professores" (siape);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519215846_InitialProfessor', '9.0.0');

COMMIT;

