version: '3.8'

services:
  api-gateway:
    build:
      context: ./backend/GatewayMicroservice
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    networks:
      - prisma-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  aluno-api:
    build:
      context: ./backend/AlunoMicroservice
      dockerfile: Dockerfile
    networks:
      - prisma-network
    #environment:
      #- ConnectionStrings__Supabase=${DATABASE_URL}

  professor-api:
    build:
      context: ./backend/ProfessorMicroservice
      dockerfile: Dockerfile
    networks:
      - prisma-network
    environment:
      - ConnectionStrings__Supabase=${DATABASE_URL}

networks:
  prisma-network:
    driver: bridge
