// <auto-generated />
using System;
using ListaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListaMicroservice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622155552_InitialLista")]
    partial class InitialLista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListaAPI.Model.Lista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtualizadoEm");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CriadoEm");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataVencimento");

                    b.Property<long>("ProfessorId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProfessorId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("ListaAPI.Model.ListaQuestao", b =>
                {
                    b.Property<long>("ListaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ListaId");

                    b.Property<long>("QuestaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("QuestaoId");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AdicionadoEm");

                    b.HasKey("ListaId", "QuestaoId");

                    b.ToTable("Lista_Questao");
                });

            modelBuilder.Entity("ListaAPI.Model.ListaTurma", b =>
                {
                    b.Property<long>("ListaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ListaId");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("TurmaId");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtribuidoEm");

                    b.HasKey("ListaId", "TurmaId");

                    b.ToTable("Lista_Turma");
                });

            modelBuilder.Entity("ListaAPI.Model.ListaQuestao", b =>
                {
                    b.HasOne("ListaAPI.Model.Lista", null)
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListaAPI.Model.ListaTurma", b =>
                {
                    b.HasOne("ListaAPI.Model.Lista", null)
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
