// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurmaAPI.Data;

#nullable disable

namespace TurmaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622144303_InitialTurma")]
    partial class InitialTurma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurmaAPI.Model.AlunoTurma", b =>
                {
                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlunoId");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("TurmaId");

                    b.Property<DateTime>("MatriculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MatriculadoEm");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Aluno_Turma");
                });

            modelBuilder.Entity("TurmaAPI.Model.ProfessorTurma", b =>
                {
                    b.Property<long>("ProfessorId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProfessorId");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("TurmaId");

                    b.Property<DateTime>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VinculadoEm");

                    b.HasKey("ProfessorId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Professor_Turma");
                });

            modelBuilder.Entity("TurmaAPI.Model.Turma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("Ano");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtualizadoEm");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Nome");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Turno");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Ano", "Turno")
                        .IsUnique();

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("TurmaAPI.Model.AlunoTurma", b =>
                {
                    b.HasOne("TurmaAPI.Model.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("TurmaAPI.Model.ProfessorTurma", b =>
                {
                    b.HasOne("TurmaAPI.Model.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });
#pragma warning restore 612, 618
        }
    }
}
