CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Resposta_Aluno" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AlunoId" bigint NOT NULL,
    "QuestaoId" bigint NOT NULL,
    "AlternativaId" bigint NOT NULL,
    "Disciplina" character varying(80) NOT NULL,
    "Vestibular" character varying(80) NOT NULL,
    "AnoProva" integer NOT NULL,
    "Dificuldade" character varying(20),
    "Acertou" boolean NOT NULL,
    "RespondidoEm" timestamp with time zone NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Resposta_Aluno" PRIMARY KEY ("ID")
);

CREATE INDEX "IX_Resposta_Aluno_AlunoId" ON "Resposta_Aluno" ("AlunoId");

CREATE UNIQUE INDEX "IX_Resposta_Aluno_AlunoId_QuestaoId" ON "Resposta_Aluno" ("AlunoId", "QuestaoId");

CREATE INDEX "IX_Resposta_Aluno_Disciplina" ON "Resposta_Aluno" ("Disciplina");

CREATE INDEX "IX_Resposta_Aluno_RespondidoEm" ON "Resposta_Aluno" ("RespondidoEm");

CREATE INDEX "IX_Resposta_Aluno_Vestibular" ON "Resposta_Aluno" ("Vestibular");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622092733_InitialDados', '9.0.1');

COMMIT;

