CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Listas" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(120) NOT NULL,
    "ProfessorId" bigint NOT NULL,
    "DataVencimento" timestamp with time zone,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone,
    CONSTRAINT "PK_Listas" PRIMARY KEY ("ID")
);

CREATE TABLE "Lista_Questao" (
    "ListaId" bigint NOT NULL,
    "QuestaoId" bigint NOT NULL,
    "AdicionadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Lista_Questao" PRIMARY KEY ("ListaId", "QuestaoId"),
    CONSTRAINT "FK_Lista_Questao_Listas_ListaId" FOREIGN KEY ("ListaId") REFERENCES "Listas" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Lista_Turma" (
    "ListaId" bigint NOT NULL,
    "TurmaId" bigint NOT NULL,
    "AtribuidoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Lista_Turma" PRIMARY KEY ("ListaId", "TurmaId"),
    CONSTRAINT "FK_Lista_Turma_Listas_ListaId" FOREIGN KEY ("ListaId") REFERENCES "Listas" ("ID") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622155552_InitialLista', '9.0.0');

COMMIT;

